<?php
$header_login_form = true;
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<?php include('comp_head.php');?>
	</head>
	<body class="en">
		<?php include("comp_mobile_nav.php"); ?>
		<section class="wrapper">
			<?php include("comp_header.php"); ?>
			<section class="content">
				<?php include("comp_asides_inner.php"); ?>
				<section class="content_area">
					<!-- <div class="banner">
						<a href=""><img src="../../assets/siteimages/banners/banner_top_main.jpg"></a>
					</div>
					<a class="FAQ_preview">
						<img src="../../assets/siteimages/backgrounds/background_faq.jpg">
					</a> -->
					<article class="tabbed faq_module">
						<section class="list_terms">
  <h1 class="mb15">Terms and Conditions of Use for the SharpStar Website</h1>
  <ol class="outer_list">
    <li>
      <strong>The  Scope of these Terms and Conditions</strong>
      <ol>
        <li>These terms and conditions of use for the SharpStar website (hereinafter called the ‘Terms’) are the terms on which
          the SharpStar website <a href="http://www.star088.com">www.star088.com</a> and its associated platforms (hereinafter
          called the ‘website’) is made available to you (hereinafter referred to as ‘the client’, ‘you’ and ’your’) and
          also cover all services, functionality, data and software (hereinafter called the ‘services’) made available via
          the website.</li>
        <li>Please read these Terms carefully before using the website and tick the box at the bottom of the page to confirm
          that you have read them. By accessing and using our website you agree to be bound by these terms whether or not
          you register through our website, log into your account or simply place a bet. You should not access the website
          or any services on it unless you agree to abide by these Terms.</li>
        <li>Certain services that are available to you on or via the website may be subject to additional terms and conditions.
          These additional terms and conditions will be notified to you when you access the relevant part(s) of the website
          and will be incorporated into the Client Agreement once you accept them and will take precedence in the event of
          any conflict between such additional terms and conditions and these Terms.</li>
      </ol>
    </li>
    <li>
      <strong>Information  About SharpStar</strong>
      <ol>
        <li>SharpStar (hereinafter referred to as ‘SharpStar’, ‘we’, ’us’ and ’our’) was launched late in 2016 as a dedicated
          spread betting service. </li>
        <li>If you have any queries, comments or complaints regarding the website and the services offered, you may contact us
          by email at <a href="mailto:cs@star088.com">cs@star088.com</a>.</li>
      </ol>
    </li>
    <li>
      <strong>Our  Services and Prices</strong>
      <ol>
        <li>SharpStar provides a spread betting service through this website, mobile technology and various other forms of electronic
          communication methods all of which utilise specialist pricing data generated by our analysts.</li>
        <li>As new technologies are developed, the ways in which we provide our services and allow you to access them may change.
          Unless explicitly stated otherwise, any new features of the services or methods through which you access the Services
          will be subject to these Terms.</li>
        <li>SharpStar reserves the right to wholly or partially refuse, reject or limit any bet, at any time, for any reason
          whatsoever.</li>
        <li>SharpStar operate strictly on an ‘execution-only’ basis. We owe you no duty of care in respect to your betting in
          any way. You are entirely responsible for all aspects of your bets including&nbsp; but not limited to your outcome,
          size, suitability, probability or perspicacity.</li>
        <li>You must realise that many markets offered by SharpStar may result in losses considerably higher than the amounts
          staked. </li>
        <li>SharpStar generally offer credit accounts. Any account recorded by us as a ‘credit account’ will have an agreed ‘credit
          limit’. This credit is not a loan agreement, nor can it be used to offset any realised losses on your account.
          It is solely a measure of how much risk SharpStar is willing to allow you on your trading account. Clients are
          welcome to ask for a higher or lower ‘credit limit’ at any time, but any final decision on your credit limit is
          solely at the discretion of SharpStar. We reserve the right to adjust your credit limit or indeed remove it altogether.
          We will confirm any credit limits, or adjustments thereof in writing.</li>
        <li>SharpStar offers a Stop Loss / Stop Profit facility. A Stop Loss / Stop Profit is designed to limit your exposure
          to both losses and profits by automatically attaching a 'stop' level when you open a position. You should therefore
          check what “stop loss” and “stop win” level limit is applied to a position prior to opening that bet with us. Note
          that stop levels vary from Index to Index and are not available on all Indices. For bets that have “stop win” and
          “stop loss” levels, those levels are the maximum number of points away from the level at which the Bet was opened
          at which the Bet will be closed. </li>
        <li>Having a Stop Loss / Stop Profit does not guarantee that your losses will not exceed the amount of your Deposit or
          credit limit.</li>
        <li>The fact that we call for a sum in a margin call does not mean that your losses are or will be limited to that sum.
          If we choose not to make a margin call in circumstances where we are entitled to do so this will not prevent us
          from making a margin call at a later date in respect of the bet(s) open on your account at the time that our entitlement
          first arose or in respect of subsequent bet(s) placed by you on your account so long as at the time of making the
          margin call your account has a negative available balance. </li>
      </ol>
    </li>
    <li>
      <strong>Volatility</strong>
      <ol>
        <li>All spread bets have a volatility requirement. This is defined here as the ‘volatility of any given market multiplied
          by the stake on that given market’. The volatility of any market varies widely, on a market to market basis. It
          is decided by SharpStar and it may be changed without notice by SharpStar. We will make every effort to make clients
          aware of the various volatility factors, but understanding that sudden changes may occur in volatile markets is
          the client’s responsibility.</li>
        <li>SharpStar may insist on a cash deposit into any given client account, if the account balance is insufficient to cover
          the volatility for any bet. Account balance is defined as any realised winnings, plus any cash deposits, plus any
          credit limit provided by SharpStar. This may also affect open bets. Open bets may move against you, such that SharpStar
          require an immediate ‘volatility payment’ if the movement of any underlying market causes open bets to go over
          the client’s account balance. Failure to make any such required volatility payment will be deemed an ‘event of
          default’, and may result in any or all of your open positions with SharpStar being closed.</li>
      </ol>
    </li>
    <li>
      <strong>Fraudulent  Activity</strong>
      <ol>
        <li>SharpStar reserves the right to suspend any account if we believe that fraudulent activity has been committed, or
          is likely to be committed. If we have reason to believe that an account is in use by a third party and not the
          named account holder, we are entitled – but not obliged – to suspend that account, withhold any cash payments due
          and close any open bets on that account.</li>
      </ol>
    </li>
    <li>
      <strong>Account  Statements</strong>
      <ol>
        <li>You are able to access your statements of account at the end of your statement period – depending on your particular
          account arrangement with SharpStar. Paper or email statements are available on request from our Customer Services
          department. You should notify us immediately if your statement is inaccurate in any way. Please note that any inaccuracies
          in the statement will not affect the validity of the relevant bet, or any other bets, in any way.</li>
      </ol>
    </li>
    <li>
      <strong>Margin  Calls</strong>
      <ol>
        <li>A margin call is a request by SharpStar to our clients for money to be paid into your account to support your open
          bets. The following rules apply to margin calls:</li>
        <li>Margin is defined as a sum of money that we are entitled to demand from you if your account moves into a negative
          cash balance. Whether your account is in deficit, and if so to what extent, is calculated by reference to the following
          formula: Your account will be in deficit to the extent that the aggregate of the net losses on your open bets (for
          example, the result of offsetting the profits against losses) plus the total volatility requirement for all your
          open bets exceeds cash held plus your credit limit. We will be entitled to demand margin from you up to the sum
          of the deficit standing to your account. If we ask you for a lesser sum then this is the sum that will be due from
          you under that margin call. Please note again, that you can in no way offset any credit balances with SharpStar
          with any negative balances with SharpStar . You should note that the fact that we call for a sum in a margin call
          does not mean that your losses are or will be limited to that sum or that we will not call for further margin subsequently,
          perhaps on the same day.</li>
      </ol>
    </li>
    <li>
      <strong>Late  Bets</strong>
      <ol>
        <li>From time to time, because of technical failure or human error, we may erroneously accept a bet on a market that:
          (a) is not an ‘in-running’ market and has already started or (b) is an ‘in-running’ market, but is not available
          to bet on because one of the for one reason or another. These examples are considered ‘late bets’. If we accept
          a late bet in error, that bet shall be void. SharpStar will void that bet and inform you of the error as soon as
          reasonably possible. </li>
      </ol>
    </li>
    <li>
      <strong>Palpable  Error</strong>
      <ol>
        <li>A palpable error is defined as a quote by us to you, whereby reason of an error on our part, the price we quote differs
          from our true market price. For example, a price of 0.5 inadvertently being quoted at 5.0. If we accept an offer
          from you to open or close a bet based upon a Pricing Error that bet shall be void and we shall: (a) void that bet
          in our records as soon as we become aware of the error; (b) inform you as soon as reasonably practicable thereafter;
          and (c) return any money attaching to that bet to you.</li>
      </ol>
    </li>
    <li>
      <strong>Market  Accuracy</strong>
      <ol>
        <li>SharpStar endeavour to keep you informed of statistics, team news, and other such relevant changes to such events
          or markets. While we offer such information in good faith, we do so without any responsibility and make no claim
          as to the accuracy or otherwise of any such information. Please be aware that any information given to you by us
          may be inaccurate. All trading decisions that relate to your betting with us must rely solely on your knowledge
          and judgement and not from any information from SharpStar.</li>
      </ol>
    </li>
    <li>
      <strong>Intellectual  Property Rights</strong>
      <ol>
        <li>The website and the copyright in all software, text, graphics, images and any other materials are owned by SharpStar
          or its licensors. You may only use the materials on our website wholly for your own personal use and solely for
          non-commercial uses except as permitted by the client agreement.</li>
        <li>You acknowledge that you may only display on a computer screen or print extracts from the website for the purposes
          stated at clause 11.1 above and without any alteration, modifications and deletions thereto. You further acknowledge
          that except as expressly provided for herein you will not alter, modify, reproduce, distribute, erase or commercially
          exploit any materials from the website without our written permission.</li>
        <li>You acknowledge that SharpStar and the SharpStar logo are trademarks of SharpStar. You further acknowledge that you
          may reproduce these trademarks without alteration and any material downloaded from this website to the extent as
          authorised in clauses 11.1 and 11.2 herein, but that you will not otherwise use, copy, adapt or erase them without
          the prior written consent of SharpStar.</li>
        <li>Subject to clauses 11.1,11.2 and11.3 herein all intellectual property rights including without limitation database
          rights, copyright, trademarks, service marks and all and any other recognised intellectual property rights in all
          material or content including but not limited to all and any pricing data, logos, graphics, photographs, animations,
          videos, underlying source code, software and text supplied or made available by us on the website, the platforms
          or by other electronic means remain at all times vested in us or our licensors as appropriate. You agree that you
          are not permitted to use, copy, reproduce, transmit, publish, display, distribute, commercially exploit, tamper
          with or create derivative works of any such material or content or assist or facilitate any third party to do so
          unless expressly authorised by these Terms or in writing by us or our licensors as appropriate.</li>
        <li>Subject to clauses 11.1,11.2 and 11.3 all names, images and logos identifying us, our partners or other third parties
          and our or their products and services contained on the website are proprietary marks and may not be reproduced
          or otherwise used without express prior written permission from the owner of the proprietary mark or trademark.</li>
        <li>You acknowledge that if you submit any information, text, photos, graphics or other content to us via the website
          or any other electronic means you grant us full rights to use such materials as we see fit and at our own discretion
          including but not limited to editing, copying, reproducing, disclosing, posting and removing such materials from
          the website.</li>
      </ol>
    </li>
    <li>
      <strong>Accessing  the Website Content and Data</strong>
      <ol>
        <li>By using the website you acknowledge and agree to all of the following personal warranties and representations:
          <ol type="a">
            <li>You are not a resident of, and are not attempting to access the website from within, a country where gambling
              and/or spread betting is prohibited. The website and/or the services do not constitute an offer, solicitation
              or invitation by us for the use of or subscription to gambling, spread betting or other services in any jurisdiction
              in which such activities are prohibited by law (including without limitation the USA and Turkey).</li>
            <li>You are at least 18 years of age or are above the legal age for gambling and/or spread betting under the relevant
              law of the country in which you are when accessing the website.</li>
            <li>You will only use the website or services, or display on a computer screen or print extracts from the website
              for your own personal use and, except as permitted by this Terms and Conditions, solely for non-commercial
              uses.</li>
            <li>You will only download or copy account information for your own personal use unless you are legally required
              to do so by an official body.</li>
            <li>All information and details provided by you to us are true, accurate and will be kept up-to-date by you.</li>
            <li>We may use the personal data and information you give us in the manner set out in our <a href="#/privacy_policy">Privacy and  Cookie Policy</a>.</li>
          </ol>
        </li>
        <li>By using the website you acknowledge and agree to all of the following personal warranties and representations:
          <ol type="a">
            <li>You will not copy, reproduce or duplicate the platforms or any content or data displayed on the website.</li>
            <li>You will not access or attempt to access the accounts of other users.</li>
            <li>You will not link to this website or frame it without our express prior written permission.</li>
            <li>You will not modify, alter, reproduce, distribute and/or commercially exploit any materials from the website
              or platforms without our prior written permission except as expressly stated herein.</li>
            <li>You will not penetrate or attempt to penetrate the website security measures or otherwise gain unauthorised access
              to the website or the servers on which the website is stored or to any platform, computer or database connected
              with the website.</li>
            <li>You will not use data mining, robots or similar data gathering and extraction tools on the website or platforms.</li>
            <li>You will not knowingly or negligently introduce viruses, Trojans, worms, logic bombs or any other harmful material
              on to the website or our servers or use the services in any way that interrupts, damages, impairs or renders
              the website or service less efficient.</li>
            <li>You will not use, attack or attempt to attack the website via a denial-of-service attack or a distributed denial-of-service
              attack.</li>
            <li>You will not use the website or services for any unlawful purpose or in any way that may encourage any criminal
              activity.</li>
            <li>You will not knowingly assist or enable any other person to do any of the above.</li>
          </ol>
        </li>
        <li>By using the website you confirm that any decisions or actions taken by you, whether or not on the basis of information
          provided on or via the website, are at your sole discretion and risk and that you will obtain individual professional
          advice where necessary before acting. We do not make any representation or give any warranty (whether express or
          implied) in respect of the website or its content including but not limited to any advice given and statements
          made by advertisers on or via the website.</li>
      </ol>
    </li>
    <li>
      <strong>Links  To and From Other Websites</strong>
      <ol>
        <li>We may provide links to other websites from time to time (including without limitation for advertising or information
          purposes). These links are provided solely for your ease of reference and as a convenience only and we do not imply
          any endorsement of the material contained in such websites or any association with their operators. We have no
          control over any third party websites and we do not make any representations as regards the content or accuracy
          of any materials on such third party websites. We are not responsible for their contents. You access these links
          at your own risk. We accept no liability in respect of any loss or damage that you may suffer by using those websites.
          The provision of links to any services as so provided by any third party are beyond our control and we will accept
          no liability for any direct, indirect, consequential, incidental or punitive losses arising out of any access by
          you and the use of any information or other material so provided.</li>
      </ol>
    </li>
    <li>
      <strong>Suspension  of Access</strong>
      <ol>
        <li>We reserve the right to suspend, restrict or terminate your access to the website or services at any time without
          notice at our discretion if we have reasonable grounds to believe you have breached any of the Terms herein and
          in particular if you have committed any of the acts prohibited in clauses 5.1 and 12.2 herein. This will not limit
          our right to take any other action against you that we consider appropriate if you commit any of the acts prohibited
          in clauses 5.1 and 12.2.</li>
      </ol>
    </li>
    <li>
      <strong>Our  Legal Obligations and Liability</strong>
      <ol>
        <li>In the event that you apply to become a client of SharpStar and receive services from us, you will be required to
          accept these Terms and Conditions. These Terms and Conditions will govern your relationship with us and our liability
          to you in respect of services rendered thereunder.</li>
        <li>Although the website is regularly updated we do not warrant that the information or materials contained in it are
          current or accurate or that any of the products or services displayed or featured on the website are available.
          We may change the information or materials appearing on our website at any time without notice.</li>
        <li>You acknowledge that except as stated herein in respect of our services, this website, its platforms and all the
          software and other materials on the website are provided to you on an ‘as is’ and ‘as available’ basis without
          any representation or warranty by us as to accuracy, timeliness and/or completeness. You further acknowledge that
          all representations and warranties whether express, implied, statutory or otherwise, including but not limited
          to any warranties or conditions of or related to accuracy, currency, merchantability, satisfactory quality or fitness,
          for a purpose or any purpose are hereby excluded to the maximum extent permitted by law. As such, we disclaim any
          representations or warranty that the website or materials will meet your requirements.</li>
        <li>You acknowledge that we will not be liable to you whether in contract, tort including in negligence and breach of
          statutory duty, strict liability or otherwise for any damage to your computer system, computer programs or loss
          of data, revenue or profits, or for any indirect, incidental, special or consequential damages of any nature whatsoever
          that you may suffer arising out of your use, delay in using or inability to access our website or in any other
          way connected with our website, including but not limited to the downloading of any software from our website,
          a distributed denial of service attack, viruses or other technologically harmful material.</li>
        <li>We disclaim any representations or warranty that the website or any software will be free from viruses, Trojans,
          worms, logic bombs or any other harmful material. You should take personal steps to protect the security of your
          computer system, computer programs and protect against loss of data both physically and electronically by utilising
          common best practice.</li>
        <li>We disclaim any representations or warranty that the information on the website will be free from errors or omissions.
          Errors and omissions excepted you must log into your account to obtain the most up-to-date pricing data as all
          prices shown when not logged in are delayed to prevent any illegal or improper use of our data. We make all reasonable
          efforts to correct any errors or omissions as soon as practicable once they have been brought to our attention.</li>
        <li>We disclaim any representations or warranty that the website or any software will be secure or uninterrupted as we
          cannot be held responsible for computer malfunctions, failure of telecommunications services or internet connections.
          In the event of system failure, maintenance, repair or any other reason beyond our control access to the website
          may be suspended temporarily and without notice.</li>
        <li>We do not accept liability for any breach of these Terms by us if such a breach is due to circumstances beyond our
          reasonable control including without limitation industrial disputes, nuclear accident, war or terrorist activity,
          acts of God, civil commotion, compliance with any law or governmental order or regulation coming into force after
          the date of these Terms, failure of technical facilities (including but not limited to internet failures, computer
          equipment failures, telecommunication equipment failures).</li>
        <li>Nothing in these Terms shall exclude or limit our liability for fraud or for death or personal injury resulting from
          our negligence or the negligence of our employees and/or agents.</li>
      </ol>
    </li>
    <li>
      <strong>Indemnity</strong>
      <ol>
        <li>You agree to indemnify, defend and hold SharpStar, its parents, subsidiaries, affiliates, officers and employees
          harmless from any loss, damage, cost, claims or demand, including reasonable legal fees, made by any third party
          or suffered by SharpStar, its parents, subsidiaries, affiliates, officers and employees in connection with or arising
          out of your use of our website in breach of these Terms or in negligence.</li>
      </ol>
    </li>
    <li>
      <strong>The  Entire Agreement and Changes to These Terms and Conditions</strong>
      <ol>
        <li>These Terms together and where relevant our <a href="#/betting_rules">Betting Rules</a> and
          <a href="#/privacy_policy">Privacy and Cookie Policy</a> and your completed application
          form contain the entire agreement between you and us relating to your access and use of the website.</li>
        <li>We reserve the right at our sole discretion to change, add to or delete any part of these Terms at any time. We will
          notify you of any such changes by posting an updated version on the website. It is your responsibility to regularly
          check the website for any changes to these Terms and by continuing to use the website and services after any such
          changes are published you are confirming your agreement to the changes.</li>
      </ol>
    </li>
    <li>
      <strong>Severance</strong>
      <ol>
        <li>If any provision of these Terms is held by a court to be invalid or unenforceable such provision shall be struck
          out and the remaining provisions shall remain in force.</li>
      </ol>
    </li>
    <li>
      <strong>Assignment  and Third Party Rights</strong>
      <ol>
        <li>You shall not assign, transfer or charge any of your rights and/or obligations under these Terms. We are entitled
          to assign, transfer and charge our rights under these Terms.</li>
        <li>Unless expressly stated, nothing in these Terms shall create or confer any rights or any other benefits to a third
          party. This does not affect our right to transfer this Agreement.</li>
      </ol>
    </li>
    <li>
      <strong>Governing  Law and Jurisdiction</strong>
      <ol>
        <li>This website, including these terms, shall be governed by the laws of the Republic of Seychelles and the Court of
          the Republic of Seychelles will have exclusive jurisdiction over any disputes arising from this website.</li>
      </ol>
    </li>
  </ol>
</section>
					</article>
				</section>
			</section>
			<?php include("comp_footer.php"); ?>
		</section>
  </div>
  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	</body>
</html>
